### ISSUE TITLE
PDI 5.x - Could not initialize class com.basho.riak.client.core.RiakNode$Builder

### ISSUE THREAD

**Issue by FabioBatSilva** [instaclick/PDI-Plugin-Step-Riak#1]
```
2015/05/20 14:26:18 - Riak Put.0 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : Unexpected error
2015/05/20 14:26:18 - Riak Put.0 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
2015/05/20 14:26:18 - Riak Put.0 -  at com.basho.riak.client.core.netty.HealthCheckDecoder.<init>(HealthCheckDecoder.java:41)
2015/05/20 14:26:18 - Riak Put.0 -  at com.basho.riak.client.core.netty.PingHealthCheck.<init>(PingHealthCheck.java:28)
2015/05/20 14:26:18 - Riak Put.0 -  at com.basho.riak.client.core.RiakNode$Builder.<clinit>(RiakNode.java:1211)
2015/05/20 14:26:18 - Riak Put.0 -  at com.basho.riak.client.api.RiakClient.newClient(RiakClient.java:243)
2015/05/20 14:26:18 - Riak Put.0 -  at com.basho.riak.client.api.RiakClient.newClient(RiakClient.java:203)
2015/05/20 14:26:18 - Riak Put.0 -  at com.instaclick.pentaho.plugin.riak.processor.ProcessorFactory.clientFor(ProcessorFactory.java:13)
2015/05/20 14:26:18 - Riak Put.0 -  at com.instaclick.pentaho.plugin.riak.processor.ProcessorFactory.processorFor(ProcessorFactory.java:18)
2015/05/20 14:26:18 - Riak Put.0 -  at com.instaclick.pentaho.plugin.riak.RiakPlugin.initPlugin(RiakPlugin.java:154)
2015/05/20 14:26:18 - Riak Put.0 -  at com.instaclick.pentaho.plugin.riak.RiakPlugin.processRow(RiakPlugin.java:48)
2015/05/20 14:26:18 - Riak Put.0 -  at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2015/05/20 14:26:18 - Riak Put.0 -  at java.lang.Thread.run(Thread.java:695)
2015/05/20 14:26:18 - Riak Put.0 - Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
2015/05/20 14:26:18 - Riak Put.0 -  at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
2015/05/20 14:26:18 - Riak Put.0 -  at java.security.AccessController.doPrivileged(Native Method)
2015/05/20 14:26:18 - Riak Put.0 -  at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
2015/05/20 14:26:18 - Riak Put.0 -  at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
2015/05/20 14:26:18 - Riak Put.0 -  at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
2015/05/20 14:26:18 - Riak Put.0 -  at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClassFromParent(KettleURLClassLoader.java:87)
2015/05/20 14:26:18 - Riak Put.0 -  at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClass(KettleURLClassLoader.java:106)
2015/05/20 14:26:18 - Riak Put.0 -  at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
2015/05/20 14:26:18 - Riak Put.0 -  ... 11 more
2015/05/20 14:26:18 - Load profiles from db.0 - Finished reading query, closing connection.
2015/05/20 14:26:18 - Json output.0 - Finished processing (I=0, O=19, R=19, W=18, U=0, E=0)
2015/05/20 14:26:18 - Riak Put.2 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : Unexpected error
2015/05/20 14:26:18 - Riak Put.0 - Finished processing (I=0, O=0, R=1, W=0, U=0, E=1)
2015/05/20 14:26:18 - load_all_profiles - Transformation detected one or more steps with errors.
2015/05/20 14:26:18 - Select values.0 - Finished processing (I=0, O=0, R=18, W=18, U=0, E=0)
2015/05/20 14:26:18 - Riak Put.5 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : Unexpected error
2015/05/20 14:26:18 - Riak Put.4 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : Unexpected error
2015/05/20 14:26:18 - Riak Put.3 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : Unexpected error
2015/05/20 14:26:18 - Riak Put.6 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : Unexpected error
2015/05/20 14:26:18 - Riak Put.7 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : Unexpected error
2015/05/20 14:26:18 - Riak Put.2 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : java.lang.NoClassDefFoundError: Could not initialize class com.basho.riak.client.core.RiakNode$Builder
2015/05/20 14:26:18 - Riak Put.2 -  at com.basho.riak.client.api.RiakClient.newClient(RiakClient.java:243)
2015/05/20 14:26:18 - Riak Put.2 -  at com.basho.riak.client.api.RiakClient.newClient(RiakClient.java:203)
2015/05/20 14:26:18 - Riak Put.2 -  at com.instaclick.pentaho.plugin.riak.processor.ProcessorFactory.clientFor(ProcessorFactory.java:13)
2015/05/20 14:26:18 - Riak Put.2 -  at com.instaclick.pentaho.plugin.riak.processor.ProcessorFactory.processorFor(ProcessorFactory.java:18)
2015/05/20 14:26:18 - Riak Put.2 -  at com.instaclick.pentaho.plugin.riak.RiakPlugin.initPlugin(RiakPlugin.java:154)
2015/05/20 14:26:18 - Riak Put.2 -  at com.instaclick.pentaho.plugin.riak.RiakPlugin.processRow(RiakPlugin.java:48)
2015/05/20 14:26:18 - Riak Put.2 -  at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2015/05/20 14:26:18 - Riak Put.2 -  at java.lang.Thread.run(Thread.java:695)
2015/05/20 14:26:18 - Riak Put.1 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : Unexpected error
2015/05/20 14:26:18 - Riak Put.7 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : java.lang.NoClassDefFoundError: Could not initialize class com.basho.riak.client.core.RiakNode$Builder
2015/05/20 14:26:18 - Riak Put.7 -  at com.basho.riak.client.api.RiakClient.newClient(RiakClient.java:243)
2015/05/20 14:26:18 - Riak Put.7 -  at com.basho.riak.client.api.RiakClient.newClient(RiakClient.java:203)
2015/05/20 14:26:18 - Riak Put.7 -  at com.instaclick.pentaho.plugin.riak.processor.ProcessorFactory.clientFor(ProcessorFactory.java:13)
2015/05/20 14:26:18 - Riak Put.7 -  at com.instaclick.pentaho.plugin.riak.processor.ProcessorFactory.processorFor(ProcessorFactory.java:18)
2015/05/20 14:26:18 - Riak Put.7 -  at com.instaclick.pentaho.plugin.riak.RiakPlugin.initPlugin(RiakPlugin.java:154)
2015/05/20 14:26:18 - Riak Put.7 -  at com.instaclick.pentaho.plugin.riak.RiakPlugin.processRow(RiakPlugin.java:48)
2015/05/20 14:26:18 - Riak Put.7 -  at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2015/05/20 14:26:18 - Riak Put.7 -  at java.lang.Thread.run(Thread.java:695)
2015/05/20 14:26:18 - Riak Put.1 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : java.lang.NoClassDefFoundError: Could not initialize class com.basho.riak.client.core.RiakNode$Builder
2015/05/20 14:26:18 - Riak Put.1 -  at com.basho.riak.client.api.RiakClient.newClient(RiakClient.java:243)
2015/05/20 14:26:18 - Riak Put.1 -  at com.basho.riak.client.api.RiakClient.newClient(RiakClient.java:203)
2015/05/20 14:26:18 - Riak Put.1 -  at com.instaclick.pentaho.plugin.riak.processor.ProcessorFactory.clientFor(ProcessorFactory.java:13)
2015/05/20 14:26:18 - Riak Put.1 -  at com.instaclick.pentaho.plugin.riak.processor.ProcessorFactory.processorFor(ProcessorFactory.java:18)
2015/05/20 14:26:18 - Riak Put.1 -  at com.instaclick.pentaho.plugin.riak.RiakPlugin.initPlugin(RiakPlugin.java:154)
2015/05/20 14:26:18 - Riak Put.1 -  at com.instaclick.pentaho.plugin.riak.RiakPlugin.processRow(RiakPlugin.java:48)
2015/05/20 14:26:18 - Riak Put.1 -  at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2015/05/20 14:26:18 - Riak Put.1 -  at java.lang.Thread.run(Thread.java:695)
2015/05/20 14:26:18 - Riak Put.6 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : java.lang.NoClassDefFoundError: Could not initialize class com.basho.riak.client.core.RiakNode$Builder
2015/05/20 14:26:18 - Riak Put.6 -  at com.basho.riak.client.api.RiakClient.newClient(RiakClient.java:243)
2015/05/20 14:26:18 - Riak Put.6 -  at com.basho.riak.client.api.RiakClient.newClient(RiakClient.java:203)
2015/05/20 14:26:18 - Riak Put.6 -  at com.instaclick.pentaho.plugin.riak.processor.ProcessorFactory.clientFor(ProcessorFactory.java:13)
2015/05/20 14:26:18 - Riak Put.6 -  at com.instaclick.pentaho.plugin.riak.processor.ProcessorFactory.processorFor(ProcessorFactory.java:18)
2015/05/20 14:26:18 - Riak Put.6 -  at com.instaclick.pentaho.plugin.riak.RiakPlugin.initPlugin(RiakPlugin.java:154)
2015/05/20 14:26:18 - Riak Put.6 -  at com.instaclick.pentaho.plugin.riak.RiakPlugin.processRow(RiakPlugin.java:48)
2015/05/20 14:26:18 - Riak Put.6 -  at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2015/05/20 14:26:18 - Riak Put.6 -  at java.lang.Thread.run(Thread.java:695)
2015/05/20 14:26:18 - Riak Put.3 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : java.lang.NoClassDefFoundError: Could not initialize class com.basho.riak.client.core.RiakNode$Builder
2015/05/20 14:26:18 - Riak Put.3 -  at com.basho.riak.client.api.RiakClient.newClient(RiakClient.java:243)
2015/05/20 14:26:18 - Riak Put.3 -  at com.basho.riak.client.api.RiakClient.newClient(RiakClient.java:203)
2015/05/20 14:26:18 - Riak Put.3 -  at com.instaclick.pentaho.plugin.riak.processor.ProcessorFactory.clientFor(ProcessorFactory.java:13)
2015/05/20 14:26:18 - Riak Put.3 -  at com.instaclick.pentaho.plugin.riak.processor.ProcessorFactory.processorFor(ProcessorFactory.java:18)
2015/05/20 14:26:18 - Riak Put.3 -  at com.instaclick.pentaho.plugin.riak.RiakPlugin.initPlugin(RiakPlugin.java:154)
2015/05/20 14:26:18 - Riak Put.3 -  at com.instaclick.pentaho.plugin.riak.RiakPlugin.processRow(RiakPlugin.java:48)
2015/05/20 14:26:18 - Riak Put.3 -  at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2015/05/20 14:26:18 - Riak Put.3 -  at java.lang.Thread.run(Thread.java:695)
2015/05/20 14:26:18 - Riak Put.4 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : java.lang.NoClassDefFoundError: Could not initialize class com.basho.riak.client.core.RiakNode$Builder
2015/05/20 14:26:18 - Riak Put.4 -  at com.basho.riak.client.api.RiakClient.newClient(RiakClient.java:243)
2015/05/20 14:26:18 - Riak Put.4 -  at com.basho.riak.client.api.RiakClient.newClient(RiakClient.java:203)
2015/05/20 14:26:18 - Riak Put.4 -  at com.instaclick.pentaho.plugin.riak.processor.ProcessorFactory.clientFor(ProcessorFactory.java:13)
2015/05/20 14:26:18 - Riak Put.4 -  at com.instaclick.pentaho.plugin.riak.processor.ProcessorFactory.processorFor(ProcessorFactory.java:18)
2015/05/20 14:26:18 - Riak Put.4 -  at com.instaclick.pentaho.plugin.riak.RiakPlugin.initPlugin(RiakPlugin.java:154)
2015/05/20 14:26:18 - Riak Put.4 -  at com.instaclick.pentaho.plugin.riak.RiakPlugin.processRow(RiakPlugin.java:48)
2015/05/20 14:26:18 - Riak Put.4 -  at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2015/05/20 14:26:18 - Riak Put.4 -  at java.lang.Thread.run(Thread.java:695)
2015/05/20 14:26:18 - Riak Put.5 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : java.lang.NoClassDefFoundError: Could not initialize class com.basho.riak.client.core.RiakNode$Builder
2015/05/20 14:26:18 - Riak Put.5 -  at com.basho.riak.client.api.RiakClient.newClient(RiakClient.java:243)
2015/05/20 14:26:18 - Riak Put.5 -  at com.basho.riak.client.api.RiakClient.newClient(RiakClient.java:203)
2015/05/20 14:26:18 - Riak Put.5 -  at com.instaclick.pentaho.plugin.riak.processor.ProcessorFactory.clientFor(ProcessorFactory.java:13)
2015/05/20 14:26:18 - Riak Put.5 -  at com.instaclick.pentaho.plugin.riak.processor.ProcessorFactory.processorFor(ProcessorFactory.java:18)
2015/05/20 14:26:18 - Riak Put.5 -  at com.instaclick.pentaho.plugin.riak.RiakPlugin.initPlugin(RiakPlugin.java:154)
2015/05/20 14:26:18 - Riak Put.5 -  at com.instaclick.pentaho.plugin.riak.RiakPlugin.processRow(RiakPlugin.java:48)
2015/05/20 14:26:18 - Riak Put.5 -  at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2015/05/20 14:26:18 - Riak Put.5 -  at java.lang.Thread.run(Thread.java:695)
2015/05/20 14:26:18 - load_all_profiles - Transformation is killing the other steps!
```

**Comment by usbrandon** [comment]
Looks like you are missing some dependencies.  Try building again with maven and let it get its dependencies?

**Comment by FabioBatSilva** [comment]
Its an existing version "2.0.2" its was compile for 4.1.x, but fails with 5.3.x
I'll probably create a new branch/release for PDI 5.x

**Comment by FabioBatSilva** [comment]
Fixed by : https://github.com/instaclick/PDI-Plugin-Step-Riak/commit/a52f1b2f0fcc476efaee147a755ca5782ebdc75a
